alias xampp='sudo /opt/lampp/manager-linux-x64.run'
alias open='xdg-open'
alias pim='xclip -selection clipboard -t image/png -o >'
alias vi='vim'
alias restart-gnome='sudo killall -3 gnome-shell'
alias keepass='$(find ~/.local/bin/ -type f -executable -print | grep KeePassXC | head -n1) >/dev/null 2>&1 &'

gatepro(){
  ~/Apps/Gatepro/bin/javaws ~/Apps/Gatepro/master.jnlp
}

dict(){
  trans $@|more
}

workon(){
  source $1/bin/activate
}

git-sync(){
  remote=${1:-"origin"}
  branch=${2:-"master"}
  git add -A
  git commit -m "Synced at $(date +'%Y-%m-%d %T')"
  git push $remote $branch
}

git-note(){
  vim /home/tupham/vtnet/git/notes.md
}

run-skydive(){
  mode=$1
  if [[ $1 == "" ]]; then
    mode=allinone
  fi
  EXEC=/home/tupham/go/bin/skydive
  sudo chown root:root $EXEC
  sudo $EXEC $mode
}

# Update tools & apps
code-update(){
  PKG=/tmp/code_latest_amd64.deb
  wget https://vscode-update.azurewebsites.net/latest/linux-deb-x64/stable -O $PKG
  sudo dpkg -i $PKG
  rm $PKG
}

subl-update(){
  PKG=/tmp/subl_latest_amd64.deb
  wget download.sublimetext.com/latest/stable/linux/x64/deb -O $PKG
  sudo dpkg -i $PKG
  rm $PKG
}

go-update(){
  PKG=/tmp/go.tar.gz
  wget "https://dl.google.com/go/$(curl https://golang.org/VERSION?m=text).linux-amd64.tar.gz" -O $PKG
  sudo tar -xzf $PKG -C /usr/local/
  rm $PKG
}

pycharm-update(){
  PKG=/tmp/pycharm.tar.gz
  wget "https://download.jetbrains.com/product?code=PCA&latest&distribution=linux" -O $PKG
  sudo tar -xzf $PKG -C /opt/
  rm $PKG
  cd /opt/pycharm-*/bin
  sh pycharm.sh
  # At the welcome menu, click Configure > Create Desktop Entry to launch PyCharm from
}

goland-update(){
  PKG=/tmp/goland.tar.gz
  wget "https://download.jetbrains.com/product?code=GO&latest&distribution=linux" -O $PKG
  sudo tar -xzf $PKG -C /opt/
  rm $PKG
  cd /opt/GoLand-*/bin
  sh goland.sh
}

# Configure tools & apps
go-config(){
  EXEC=$(which go)
  if [[ $? -eq 0 ]]; then
    mkdir -p $HOME/go
    echo "export GOROOT=${EXEC:0:-7}" >> ~/.bashrc
    echo "export GOPATH=$HOME/go" >> ~/.bashrc
    echo "export PATH=\$GOPATH/bin:\$GOROOT/bin:\$PATH" >> ~/.bashrc
    source ~/.bashrc
  else
    echo "Please install golang on your system first."
  fi
}
