alias xampp='sudo /opt/lampp/manager-linux-x64.run'
alias open='xdg-open'
alias pim='xclip -selection clipboard -t image/png -o >'
alias vi='vim'

dict(){
  trans $@|more
}

workon(){
  source $1/bin/activate
}

git-sync(){
  remote=$([ "$1" == "" ] && echo "origin" || echo "$1")
  branch=$([ "$2" == "" ] && echo "master" || echo "$2")
  git add *
  git commit -m "Synced at $(date +'%Y-%m-%d %T')"
  git push $remote $branch
}

eng-note() {
  vim /home/tupham/vtnet/english/sapiens.md
}
