# Global environment
export EDITOR=/usr/local/bin/vim
export GOROOT=/usr/local/go
export GOPATH=$HOME/go
export PATH=$GOPATH/bin:$GOROOT/bin:$HOME/.local/bin:$PATH

# Colorize some commands
alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

# Configure typewritten
fpath+=$HOME/.zsh/typewritten
autoload -U promptinit; promptinit
prompt typewritten
export TYPEWRITTEN_CURSOR="block"

# Configure completion
fpath+=$HOME/.zsh/completion
autoload -U compinit; compinit
#autoload -Uz compinit; compinit -i

# Configure Tilix
if [ $TILIX_ID ] || [ $VTE_VERSION ]; then
    source /etc/profile.d/vte-2.91.sh
fi

# Import aliases
if [ -f "$HOME/.zsh_aliases" ]; then source "$HOME/.zsh_aliases"; fi
if [ -f "$HOME/.zsh_aliases.local" ]; then source "$HOME/.zsh_aliases.local"; fi

# Disable FocusIn/FocusOut (https://unix.stackexchange.com/questions/480052/how-do-i-detect-whether-my-terminal-has-focus-in-the-gui-from-a-shell-script/480138#480138)
echo -ne '\e[?1004l'
